# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sobrelaapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 450)
        Dialog.setWindowFilePath("")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 451))
        self.frame.setStyleSheet("color: rgb(122, 145, 191); \n"
";\n"
"background-color: rgb(75, 43, 68);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tituloApp = QtWidgets.QLabel(self.frame)
        self.tituloApp.setGeometry(QtCore.QRect(0, 0, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.tituloApp.setFont(font)
        self.tituloApp.setStyleSheet("color: rgb(174, 181, 191);")
        self.tituloApp.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloApp.setObjectName("tituloApp")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 381, 301))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("\n"
"color: rgb(174, 181, 191);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.botOK = QtWidgets.QPushButton(self.frame)
        self.botOK.setGeometry(QtCore.QRect(170, 380, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botOK.setFont(font)
        self.botOK.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 159, 50);\n"
"    border-radius: 10px;\n"
"    color: rgb(60, 47, 69);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(90, 47, 69);\n"
"    color: rgb(222, 159, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 183, 57);\n"
"    color: rgb(60, 47, 69);\n"
"}")
        self.botOK.setObjectName("botOK")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowFlag(Qt.FramelessWindowHint)
        Dialog.setWindowTitle(_translate("Dialog", "Sobre la apllicación"))
        self.tituloApp.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">i</span>X</p></body></html>"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">iX</span> es una aplicación programada en Python 3.8 que utiliza las librerías <a href=\"https://github.com/IfcOpenShell/IfcOpenShell\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">IfcOpenShell</span></a>, <a href=\"https://www.riverbankcomputing.com/software/pyqt/\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">PyQt5</span></a>, <a href=\"https://pandas.pydata.org/\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">Pandas</span></a> y <a href=\"https://pypi.org/project/XlsxWriter/\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">XlsxWriter</span></a> para extraer información de los modelos BIM en el formato abierto IFC, generando un reporte en hojas de cálculo (*.xlsx) que puede ser revisado y comprendido por humanos. Compatibilidad probada con IFC 4, posiblemente también funciona con IFC 2x3. Si se detectan problemas o fallos en su funcionamiento, escribir a <a href=\"mailto:ix@bimfluent.cl\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">ix@bimfluent.cl</span></a>.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Esta aplicación fue creada por <a href=\"https://github.com/pag0dy\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">pagody</span></a>, con la intención de facilitar la revisión de la información de los modelos BIM, sin la necesidad de utilizar software de pago. </p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"><br />Esta obra está bajo una Licencia </span><a href=\"https://www.gnu.org/licenses/gpl-3.0.html\"><span style=\" font-size:8pt; text-decoration: underline; color:#de9f32;\">GNU General Public License v3.0</span></a><span style=\" font-size:8pt;\">. </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#de9f32;\">iX versión 0.1 © 2020 pagody </span></p></body></html>"))
        self.botOK.setText(_translate("Dialog", "OK"))
        self.botOK.clicked.connect(Dialog.reject)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
